before:
  hooks:

builds:
  - id: aserto-idp-plugin-json
    main: ./cmd/aserto-idp-plugin-json
    binary: aserto-idp-plugin-json
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X pkg/config.ver={{.Version}}
      - -X pkg/config.commit={{.ShortCommit}}
      - -X pkg/config.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - README.md
    name_template: "aserto-idp-plugin-json{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

blobs:
  - provider: gs
    bucket: aserto-idp-cli
    folder: "plugins/aserto-idp-plugin-json/{{ .Major }}/{{ .Version }}"

release:
  github:
    owner: aserto-dev
    name: aserto-idp-plugin-json

  draft: false
  prerelease: false
  name_template: "aserto-idp-plugin-json {{.Tag}}"